# Generated by Django 4.2.11 on 2024-03-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
