# Generated by Django 5.0.2 on 2024-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='bgColor',
        ),
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
        migrations.AddField(
            model_name='part',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
