# Generated by Django 4.2.11 on 2024-03-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='id',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
